#!/bin/bash 
#--------------------------------------------------
# Bootstrap an instance of Ubuntu Server 16.04 to
# be a template for building software development
# environments. 
# 
# Run this script as root.
# Assumes fresh install of Ubuntu Server 16.04.
# 
# This script installs a few things and sets some
# configuration values to bring the instance up 
# to a state that it can run Chef, then it starts
# chef-client to complete the provisioning using
# Chef recipes. 
#
# Version 0.1.0 
# 22 Apr 2018
#--------------------------------------------------

[[ $EUID -ne 0 ]] && 'Please run the bootstrap script as root' && exit 1 

apt update -y
apt dist-upgrade -y
# software-properties-common must be installed to make add-apt-repository available
apt install -y software-properties-common
add-apt-repository -y ppa:brightbox/ruby-ng 
apt update -y
apt install -y openssh-server

printf "Enabling root login via ssh...\n" 
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bkp 
sed -i '/PermitRootLogin/ c\PermitRootLogin yes' /etc/ssh/sshd_config 

apt install -y build-essential \ 
    linux-headers-`uname -r` \    
    dkms \
    ruby2.4 \ 
    ruby2.4-dev \ 
    ruby-bundler \ 
    curl 

printf "Installing Chef DK.\n" 
curl https://omnitruck.chef.io/install.sh | bash -s -- -P chefdk -c stable -v 2.0.28

printf "Copying files from distribution directories to target directories.\n"
cp scripts/* /usr/local/bin 
mkdir -p /root/chef-repo/cookbooks/ubuntu_prep/spec/unit
mkdir -p /root/chef-repo/cookbooks/ubuntu_prep/recipes 
cp ubuntu_prep/Gemfile /root/chef-repo/cookbooks/ubuntu_prep/. 
cp ubuntu_prep/Rakefile /root/chef-repo/cookbooks/ubuntu_prep/.
cp -r ubuntu_prep/recipes/* /root/chef-repo/cookbooks/ubuntu_prep/recipes
cp spec/spec_helper.rb /root/chef-repo/cookbooks/ubuntu_prep/spec/spec_helper.rb 
cp -r ubuntu_prep/spec/unit/recipes/* /root/chef-repo/cookbooks/ubuntu_prep/spec/unit/recipes 

printf "Executing Chef to complete provisioning the instance.\n"
cd /root/chef-repo/cookbooks 
chef-client --local-mode --override-runlist ubuntu_prep 

