#!/bin/bash 
# Run chef-client to process a single cookbook or recipe.
# $1 can be cookbook or cookbook::recipe 

[[ -z "$1" ]] && echo 'Please pass the name of a cookbook or a cookbook::recipe as an argument' && exit 1 

pushd /root/chef-repo/cookbooks 
chef-client --local-mode --override-runlist "$1"
popd 
